// Texte für das Projekt "Rauschen" (generative Kunst), Deutsch und Englisch.
module.exports = {
  de: {
    intro:
      "Gib ein Wort ein, z. B. deinen Namen, und daraus entsteht ein Bild, das es so nur einmal gibt. Der Name passt doppelt: Gemalt wird mit Perlin-<em>Rauschen</em>, und Robert <em>Rauschenberg</em> war schließlich auch Künstler.",
    seed: "Dein Wort",
    placeholder: "z. B. Denni",
    random: "Zufall",
    palette: "Farben",
    style: "Stil",
    paletteAuto: "Überrasch mich",
    palettes: {
      theme: "Wie die Seite",
      sunset: "Abendrot",
      ocean: "Tiefsee",
      forest: "Wald",
      ink: "Tusche",
      neon: "Neon",
    },
    styles: { flow: "Strömung", brush: "Pinsel", dots: "Konfetti" },
    download: "Als Bild speichern",
    share: "Link kopieren",
    copied: "Link kopiert!",
    copyFailed: "Kopieren ging nicht, der Link steht in der Adresszeile.",
    painting: "Malt …",
    done: "Fertig. Tipp: Klick ins Bild für mehr Farbe.",
    canvasLabel: "Generiertes Kunstwerk. Klicken fügt an der Stelle neue Striche hinzu.",
    no: "Nr.",
    adjectives: [
      "Leise", "Wilde", "Verlorene", "Goldene", "Schlafende", "Elektrische",
      "Flüssige", "Ferne", "Müde", "Glühende", "Zarte", "Kosmische",
      "Heimliche", "Laute", "Späte", "Gefaltete",
    ],
    nouns: [
      "Brandung", "Stunde", "Strömung", "Erinnerung", "Spur", "Welle",
      "Melodie", "Kurve", "Stille", "Nacht", "Bewegung", "Landschaft",
      "Brise", "Ahnung", "Galaxie", "Schleife",
    ],
    randomWords: [
      "Kaffee", "Montag", "Gewitter", "Pizza", "Sternschnuppe", "Fernweh",
      "Lagerfeuer", "Regenbogen", "Nordlicht", "Bergluft", "Ostsee", "Glühwein",
    ],
  },
  en: {
    intro:
      "Type a word, your name for example, and it turns into a picture that exists exactly once. The name works twice: it is painted with Perlin <em>noise</em> (German: <em>Rauschen</em>), and Robert <em>Rauschenberg</em> was an artist too.",
    seed: "Your word",
    placeholder: "e.g. Denni",
    random: "Random",
    palette: "Colours",
    style: "Style",
    paletteAuto: "Surprise me",
    palettes: {
      theme: "Match the site",
      sunset: "Sunset",
      ocean: "Deep sea",
      forest: "Forest",
      ink: "Ink",
      neon: "Neon",
    },
    styles: { flow: "Flow", brush: "Brush", dots: "Confetti" },
    download: "Save as image",
    share: "Copy link",
    copied: "Link copied!",
    copyFailed: "Couldn't copy, the link is in the address bar.",
    painting: "Painting …",
    done: "Done. Tip: click into the picture for more colour.",
    canvasLabel: "Generated artwork. Clicking adds new strokes at that spot.",
    no: "No.",
    adjectives: [
      "Quiet", "Wild", "Lost", "Golden", "Sleeping", "Electric",
      "Liquid", "Distant", "Tired", "Glowing", "Gentle", "Cosmic",
      "Secret", "Loud", "Late", "Folded",
    ],
    nouns: [
      "Surf", "Hour", "Current", "Memory", "Trace", "Wave",
      "Melody", "Curve", "Silence", "Night", "Motion", "Landscape",
      "Breeze", "Hunch", "Galaxy", "Loop",
    ],
    randomWords: [
      "coffee", "Monday", "thunderstorm", "pizza", "shooting star", "wanderlust",
      "campfire", "rainbow", "aurora", "mountain air", "seaside", "hot cocoa",
    ],
  },
};
